apiVersion: v1
kind: Pod
metadata:
  name: test-workload-identity
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-sa
  containers:
  - name: app
    image: acrlabpdeqvtm5.azurecr.io/test-app:v2
    imagePullPolicy: Always
